apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server
  namespaces: ml-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: api
        image: python:3.9-slim
        env:
        - name: MODEL_VERSION
          value: "v1" # <--- We will automate changing this!
